### ISSUE TITLE
Breaking changes version 1.0.0-beta-1

### ISSUE THREAD

**Issue by BenjaminOddou** [vueuse/schema-org#15]
Hello @harlan-zw 👋,

I remarked that in the new version `1.0.0-beta-.1` I had a problem when using `nuxt generate` command:

```shell
 ERROR  [nitro] [dev] [unhandledRejection] ReferenceError: defineWebPagePartial is not defined                                                                                    16:00:05

  ├─ / (16ms) (Error: [500] Internal Server Error)      
```

**Comment by BenjaminOddou** [comment]
I found also that the global configuration is throwing errors :

```ts
export default defineNuxtConfig({
  schemaOrg: {
    canonicalHost: 'https://example.com',
    defaultLanguage: 'en-AU'
    // other options
  },
})
```

error messages:
```shell
Cannot assign type '{ canonicalHost: string; defaultLanguage: string; }' to type 'Partial<ModuleOptions>'.
An object literal can only specify known properties, and 'canonicalHost' does not exist in type 'Partial<ModuleOptions>'.ts(2322)
types.d.ts(5, 26): Expected type comes from property 'schemaOrg', which is declared here on type 'NuxtConfig'
```

```shell
 WARN  [WARN] @vueuse/schema-org: Missing required host from createSchemaOrg.  
```


`node_modules/nuxt-schema-org/dist/types.d.ts` file:
```ts
import { ModuleOptions, ModuleHooks } from './module'

declare module '@nuxt/schema' {
  interface NuxtConfig { ['schemaOrg']?: Partial<ModuleOptions> }
  interface NuxtOptions { ['schemaOrg']?: ModuleOptions }
  interface NuxtHooks extends ModuleHooks {}
}

export { default } from './module'
```

**Comment by harlan-zw** [comment]
Hey @BenjaminOddou 

Thanks for your interest in using the beta! 

I'm testing out the beta on a few sites at the moment and it's not quite stable yet. The v1 major bump will indeed have some breaking changes, I plan to document this properly and provide a migration guide once it is stable.

Should have something within the next ~2 days depending on how this bug squashing goes

**Comment by BenjaminOddou** [comment]
Hello @harlan-zw,

I can see that you're working hard on this at the moment! I will try to test the module with the last beta version and let you know in case of bugs. Thank you for your support and the great work on the module ! 🙏

**Comment by shtse8** [comment]
I am still confusing on 
```
[@vueuse/schema-org] Failed to find plugin, you may have forgotten to apply app.use(schemaOrg)
```

**Comment by harlan-zw** [comment]
Hey @shtse8 

Happy to assist with this, can you confirm which version of the package you're using and with what framework / version?

**Comment by harlan-zw** [comment]
> I am still confusing on
> 
> ```
> [@vueuse/schema-org] Failed to find plugin, you may have forgotten to apply app.use(schemaOrg)
> ```
> 
> ```
> [Vue warn]: inject() can only be used inside setup() or functional components.
> ```
> 
> ```
> Uncaught SyntaxError: The requested module '/node_modules/@vueuse/schema-org/dist/runtime/index.mjs' does not provide an export named 'SchemaOrgEvent' (at components.client.mjs:56:10)
> ```

Actually looks like the `SchemaOrgEvent` component wasn't exported, a fix is available in 1.0.0-beta.13

**Comment by shtse8** [comment]
> Hey @shtse8
> 
> Happy to assist with this, can you confirm which version of the package you're using and with what framework / version?

I am using latest `1.0.0-beta.12` and `1.0.0-beta.13`

Problem still exists. Anyway, how can I import module in this version?

<img width="544" alt="image" src="https://user-images.githubusercontent.com/8020099/185101859-d9a6a39a-7520-40aa-85bb-9ebf98994bf9.png">

<img width="247" alt="image" src="https://user-images.githubusercontent.com/8020099/185101940-659cfbfa-fc54-48b5-983b-8e2e95c56725.png">

**Comment by harlan-zw** [comment]
> > Hey @shtse8
> > Happy to assist with this, can you confirm which version of the package you're using and with what framework / version?
> 
> I am using latest `1.0.0-beta.12` and `1.0.0-beta.13`
> 
> Problem still exists. Anyway, how can I import module in this version?
> 
> <img alt="image" width="544" src="https://user-images.githubusercontent.com/8020099/185101859-d9a6a39a-7520-40aa-85bb-9ebf98994bf9.png">
> 
> <img alt="image" width="247" src="https://user-images.githubusercontent.com/8020099/185101940-659cfbfa-fc54-48b5-983b-8e2e95c56725.png">
> 
> I understand it should be changed to auto import now, but my IDE cannot identify it. Also, while running, it still throw many erros while it was working perfect in 0.x version.
> 
> ```
> [Vue warn]: inject() can only be used inside setup() or functional components.
> New request: undefined /__nuxt_error?url=/@penicillinfreckled/%25E6%25B3%2595%25E5%25AE%2598%25E8%25A3%2581%25E5%2586%25B3-%25E4%25BB%25A5%25E5%25A4%25AA%25E5%259D%258A%25E5%25BC%2580%25E5%258F%2591%25E4%25BA%25BA%25E5%2591%2598%25E7%25BB%25B4%25E5%2590%2589%25E5%25B0%2594-%25E6%25A0%25BC%25E9%2587%258C%25E8
> %258F%25B2%25E6%2596%25AF-virgil-griffith-%25E5%25B0%2586%25E8%25A2%25AB%25E9%2587%258A%25E6%2594%25BE-2777&statusCode=500&statusMessage=Internal+Server+Error&message=[@vueuse/schema-org]+Failed+to+find+plugin,+you+may+have+forgotten+to+apply+app.use(schemaOrg)&description=%3Cpre%3E%3Cspan+class=%22stack+internal%22%3Eat+Module.injectSchemaOrg+(/d:/project/node_modules/@vueuse/schema-org/dist/runtime/composables/injectSchemaOrg.mjs:10:11)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+setup+(D:/project/app.vue:54:45)%3C/span%3E%3C/pre%3E&data
> [Vue warn]: Unhandled error during execution of setup function
>   at <App>
> [nuxt] [request error] [unhandled] [500] [@vueuse/schema-org] Failed to find plugin, you may have forgotten to apply app.use(schemaOrg)
>   at Module.injectSchemaOrg (/d:/project/node_modules/@vueuse/schema-org/dist/runtime/composables/injectSchemaOrg.mjs:10:11)
>   at setup (D:/project/app.vue:54:45)
> New request: projectdev.news:3000 /@penicillinfreckled/%E6%B3%95%E5%AE%98%E8%A3%81%E5%86%B3-%E4%BB%A5%E5%A4%AA%E5%9D%8A%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E7%BB%B4%E5%90%89%E5%B0%94-%E6%A0%BC%E9%87%8C%E8%8F%B2%E6%96%AF-virgil-griffith-%E5%B0%86%E8%A2%AB%E9%87%8A%E6%94%BE-2777
> [Vue warn]: inject() can only be used inside setup() or functional components.
> New request: undefined /__nuxt_error?url=/@penicillinfreckled/%25E6%25B3%2595%25E5%25AE%2598%25E8%25A3%2581%25E5%2586%25B3-%25E4%25BB%25A5%25E5%25A4%25AA%25E5%259D%258A%25E5%25BC%2580%25E5%258F%2591%25E4%25BA%25BA%25E5%2591%2598%25E7%25BB%25B4%25E5%2590%2589%25E5%25B0%2594-%25E6%25A0%25BC%25E9%2587%258C%25E8
> %258F%25B2%25E6%2596%25AF-virgil-griffith-%25E5%25B0%2586%25E8%25A2%25AB%25E9%2587%258A%25E6%2594%25BE-2777&statusCode=500&statusMessage=Internal+Server+Error&message=[@vueuse/schema-org]+Failed+to+find+plugin,+you+may+have+forgotten+to+apply+app.use(schemaOrg)&description=%3Cpre%3E%3Cspan+class=%22stack+internal%22%3Eat+Module.injectSchemaOrg+(/d:/project/node_modules/@vueuse/schema-org/dist/runtime/composables/injectSchemaOrg.mjs:10:11)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+setup+(D:/project/app.vue:54:45)%3C/span%3E%3C/pre%3E&data
> [Vue warn]: Unhandled error during execution of setup function
>   at <App>
> [nuxt] [request error] [unhandled] [500] [@vueuse/schema-org] Failed to find plugin, you may have forgotten to apply app.use(schemaOrg)
>   at Module.injectSchemaOrg (/d:/project/node_modules/@vueuse/schema-org/dist/runtime/composables/injectSchemaOrg.mjs:10:11)
>   at setup (D:/project/app.vue:54:45)
> ```

Which Nuxt version? And any ideas on how to replicate? Latest package with Nuxt RC 8 seems to work okay https://stackblitz.com/edit/nuxt-starter-w93wzt?file=README.md. Maybe a windows issue?

Keep in mind this is a beta release so is not guaranteed to be stable, thanks for helping me find issues :)

**Comment by shtse8** [comment]
> > > Hey @shtse8
> > > Happy to assist with this, can you confirm which version of the package you're using and with what framework / version?
> > 
> > 
> > I am using latest `1.0.0-beta.12` and `1.0.0-beta.13`
> > Problem still exists. Anyway, how can I import module in this version?
> > <img alt="image" width="544" src="https://user-images.githubusercontent.com/8020099/185101859-d9a6a39a-7520-40aa-85bb-9ebf98994bf9.png">
> > <img alt="image" width="247" src="https://user-images.githubusercontent.com/8020099/185101940-659cfbfa-fc54-48b5-983b-8e2e95c56725.png">
> > I understand it should be changed to auto import now, but my IDE cannot identify it. Also, while running, it still throw many erros while it was working perfect in 0.x version.
> > ```
> > [Vue warn]: inject() can only be used inside setup() or functional components.
> > New request: undefined /__nuxt_error?url=/@penicillinfreckled/%25E6%25B3%2595%25E5%25AE%2598%25E8%25A3%2581%25E5%2586%25B3-%25E4%25BB%25A5%25E5%25A4%25AA%25E5%259D%258A%25E5%25BC%2580%25E5%258F%2591%25E4%25BA%25BA%25E5%2591%2598%25E7%25BB%25B4%25E5%2590%2589%25E5%25B0%2594-%25E6%25A0%25BC%25E9%2587%258C%25E8
> > %258F%25B2%25E6%2596%25AF-virgil-griffith-%25E5%25B0%2586%25E8%25A2%25AB%25E9%2587%258A%25E6%2594%25BE-2777&statusCode=500&statusMessage=Internal+Server+Error&message=[@vueuse/schema-org]+Failed+to+find+plugin,+you+may+have+forgotten+to+apply+app.use(schemaOrg)&description=%3Cpre%3E%3Cspan+class=%22stack+internal%22%3Eat+Module.injectSchemaOrg+(/d:/project/node_modules/@vueuse/schema-org/dist/runtime/composables/injectSchemaOrg.mjs:10:11)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+setup+(D:/project/app.vue:54:45)%3C/span%3E%3C/pre%3E&data
> > [Vue warn]: Unhandled error during execution of setup function
> >   at <App>
> > [nuxt] [request error] [unhandled] [500] [@vueuse/schema-org] Failed to find plugin, you may have forgotten to apply app.use(schemaOrg)
> >   at Module.injectSchemaOrg (/d:/project/node_modules/@vueuse/schema-org/dist/runtime/composables/injectSchemaOrg.mjs:10:11)
> >   at setup (D:/project/app.vue:54:45)
> > New request: projectdev.news:3000 /@penicillinfreckled/%E6%B3%95%E5%AE%98%E8%A3%81%E5%86%B3-%E4%BB%A5%E5%A4%AA%E5%9D%8A%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E7%BB%B4%E5%90%89%E5%B0%94-%E6%A0%BC%E9%87%8C%E8%8F%B2%E6%96%AF-virgil-griffith-%E5%B0%86%E8%A2%AB%E9%87%8A%E6%94%BE-2777
> > [Vue warn]: inject() can only be used inside setup() or functional components.
> > New request: undefined /__nuxt_error?url=/@penicillinfreckled/%25E6%25B3%2595%25E5%25AE%2598%25E8%25A3%2581%25E5%2586%25B3-%25E4%25BB%25A5%25E5%25A4%25AA%25E5%259D%258A%25E5%25BC%2580%25E5%258F%2591%25E4%25BA%25BA%25E5%2591%2598%25E7%25BB%25B4%25E5%2590%2589%25E5%25B0%2594-%25E6%25A0%25BC%25E9%2587%258C%25E8
> > %258F%25B2%25E6%2596%25AF-virgil-griffith-%25E5%25B0%2586%25E8%25A2%25AB%25E9%2587%258A%25E6%2594%25BE-2777&statusCode=500&statusMessage=Internal+Server+Error&message=[@vueuse/schema-org]+Failed+to+find+plugin,+you+may+have+forgotten+to+apply+app.use(schemaOrg)&description=%3Cpre%3E%3Cspan+class=%22stack+internal%22%3Eat+Module.injectSchemaOrg+(/d:/project/node_modules/@vueuse/schema-org/dist/runtime/composables/injectSchemaOrg.mjs:10:11)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+setup+(D:/project/app.vue:54:45)%3C/span%3E%3C/pre%3E&data
> > [Vue warn]: Unhandled error during execution of setup function
> >   at <App>
> > [nuxt] [request error] [unhandled] [500] [@vueuse/schema-org] Failed to find plugin, you may have forgotten to apply app.use(schemaOrg)
> >   at Module.injectSchemaOrg (/d:/project/node_modules/@vueuse/schema-org/dist/runtime/composables/injectSchemaOrg.mjs:10:11)
> >   at setup (D:/project/app.vue:54:45)
> > ```
> 
> Which Nuxt version? And any ideas on how to replicate? Latest package with Nuxt RC 8 seems to work okay https://stackblitz.com/edit/nuxt-starter-w93wzt?file=README.md. Maybe a windows issue?
> 
> Keep in mind this is a beta release so is not guaranteed to be stable, thanks for helping me find issues :)

I am using rc8 too. I don't know exactly how to reproduce. I will try to create a simple project to figure out.

**Comment by harlan-zw** [comment]
Hi all, v1 is now at a [stable release](https://vue-schema-org.netlify.app/posts/v1-release).

Going to close this issue off, but if you have any issues with v1 please submit a new issue.

**Comment by harlan-zw** [comment]
Hey @shtse8, sorry you're still having issues. I've tried my best to replicate issues before release but seems I've missed something

Can you try out version `1.0.3-beta.4` and let me know if it helps

**Comment by shtse8** [comment]
> Hey @shtse8, sorry you're still having issues. I've tried my best to replicate issues before release but seems I've missed something
> 
> Can you try out version `1.0.3-beta.4` and let me know if it helps
> 
> It may come down to a windows problem which I couldn't replicate via github actions

after updating to `1.1.0-beta.0`

```
Missing "./dist/runtime-simple" export in "@vueuse/schema-org" package                                                                                                                01:50:38  

  at bail (/D:/project/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:33617:8)
  at resolve (/D:/project/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:33694:10)
  at resolveExports (/D:/project/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:34717:12)
  at resolveDeepImport (/D:/project/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:34735:31)
  at tryNodeResolve (/D:/project/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:34452:20)
  at Context.resolveId (/D:/project/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:34189:32)
  at Object.resolveId (/D:/project/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35511:55)
  at processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Context.resolve (/D:/project/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35276:23)
  at async Object.resolveId (/D:/project/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35511:32)
```

Do I miss something?

**Comment by harlan-zw** [comment]
I've released `1.1.0-beta.1` which again may have fixed this. I'll need to dig out my old windows laptop to try and replicate this otherwise

**Comment by shtse8** [comment]
> I've released `1.1.0-beta.1` which again may have fixed this. I'll need to dig out my old windows laptop to try and replicate this otherwise

For `1.1.0-beta.1`

```ts
[Vue warn]: inject() can only be used inside setup() or functional components.
[@vueuse/schema-org] Failed to find plugin, you may have forgotten to apply app.use(schemaOrg)
```

```html
<script type="application/ld+json" data-id="schema-org-graph" data-meta-body="true">{
"@context": "https://schema.org",
"@graph": []
}</script>
```

**Comment by jimchampagne** [comment]
Hello! I've been struggling with this issue aswel @shtse8.

I also have the same problems on my windows environment. I am using Nuxt RC.12 at the moment and got things working again after trying several versions of 'nuxt-schema-org'. After downgrading to version 0.6.5 everything worked again.

So 0.6.5 seems stable for windows and the latest Nuxt Release Candidate!

Hope this helps someone!

**Comment by harlan-zw** [comment]
These issues should be sorted with the v2 release. Let me know if you have any issues with the migration
